- include_vars: _secrets.yml

- name: Request token from AUTH API
  uri:
    url: "{{ IAM_AUTH_URL }}"
    method: POST
    body_format: raw
    follow_redirects: all
    status_code: 201
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    body: "{{ lookup('template', 'roles/token/templates/request.json.j2',convert_data=True)|to_json }}" 
  register: token

- set_fact: 
#    OS_USER_DOMAIN_ID: "{{ (token.content|from_json)['token']['user']['domain']['id'] }}"
    OS_USER_DOMAIN_ID: "{{ (token.content|from_json)|json_query('token.user.domain.id') }}"

# - debug:
#     msg: "{{ token }}"
