- name: Lookup eip_id
  include: lookup.yml

- name: Send request to API (show EIP)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/publicips/{{ eip_id}}"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: floatingipdetails

- debug:
    msg: "{{  floatingipdetails.json }}"
