
- name: fetch zonerecords from ini
  set_fact: 
    zonerecords: "{{ item }}"
  with_ini: zonerecord[1-9] section=dnszonerecords file=tenant.ini re=true
  register: zonerecord_reg

- name: make a list from zonerecords
  set_fact: 
    zonerecord_list: "{{ zonerecord_reg.results | map(attribute='ansible_facts.zonerecords') | list }}"

- name: fetch zones from ini
  set_fact: 
    zones: "{{ item }}"
  with_ini: zone[1-9] section=dnszones file=tenant.ini re=true
  register: zone_reg

- name: make a list from zones
  set_fact: 
    zone_list: "{{ zone_reg.results | map(attribute='ansible_facts.zones') | list }}"

- name: Send zone request to API
  vars:
    zone_list_part: "{{ item.split(';') }}"
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,400
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/zonerecord_helper/templates/zone.json.j2')|to_json }}"
  register: zone
  with_items:
    - "{{ zone_list }}"

- name: Request zone list from API
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones"
    method: GET
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: zonelist_result

- name: send zonerecord request to API 
  vars:
    zonerecord_part: "{{ item.split(';') }}"
    zone_id: "{{ (zonelist_result.content|from_json)|json_query(\"zones[?name=='\" + zonerecord_part[0] + \"'].id|[0]\") }}"
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones/{{ zone_id }}/recordsets"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,400
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/zonerecord_helper/templates/zonerecord.json.j2')|to_json }}"
  register: zonerecord
  with_items:
    - "{{ zonerecord_list }}"

