- name: Send request to API (create security group)
#  vars:
#    secgroup_name: "{{ item }}"
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/security-groups"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  when: secgroups is defined
  register: secgroupcreate
  with_items:
    - "{{ secgroups }}"
  loop_control:
    loop_var: secgroup_name

- name: Create securiy group rules
  include: rule_create.yml
  with_items:
    - "{{ secgroups }}"
  loop_control:
    loop_var: secgroup_name
