- name: Lookup secgroup_id
  include: lookup.yml

- name: Send request to API
  uri:
    url: "{{ AUTH_URL_VPC }}/v2.0/security-groups/{{ secgroup_id }}"
    method: DELETE
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,204
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgroup

- debug:
    msg: "{{ secgroup }}"
