- name: Lookup secgroup_id
  include: lookup.yml

- name: Request secgroup detail from API
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/security-groups/{{ secgroup_id }}"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgroupdetail
  when:
    - secgroup_id is defined

- debug:
    msg: "{{ secgroupdetail.json }}"
  when:
    - secgroup_id is defined
