stages:
- check
- package

lint:
  stage: check
  script:
    - sudo apt-get -y install python-pip
    - sudo pip install yamllint
    - find roles/ -name "*.yml" | xargs ansible-lint

package:
   stage: package
   script:
     - sudo apt-get -y install ruby ruby-dev rubygems build-essential
     - sudo gem install --no-ri --no-rdoc fpm
     - fpm -s dir -t deb -d ansible -v "01-${CI_BUILD_REF_NAME}-$(date +%s)" -n ansible-roles-otc  --iteration 1 -x .git -x .gitignores --description "Ansible roles for Open Telekom Cloud" --prefix /etc/ansible/roles roles
   artifacts:
     paths:
     - ansible-roles-otc*.deb
     expire_in: 1 week
