---

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: vpc_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: subnet_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: secgroup_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: secgrouprule_helper

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: keypair_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: eip_apply

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var.yml
  roles:
    - role: token
    - role: ptrrecord_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: ecs_create
    - role: job

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: elb_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: elb_listener_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: lookup_name
    - role: elb_healthcheck_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var_default.yml
    - tenant_var.yml
  roles:
    - role: lookup_name
    - role: backend_member_helper
      when: backend_members is defined
