---

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: vpc_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: subnet_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: secgroup_create

# - debug:
#     msg: "{{ item }}"
#   with_ini:
#     - secgroup_rule[1-2]
#     - section: {{ ecs_name }}
#     - file: "tenant.ini"
#     - re: true
#tasks:
#    - name: Let's split
#      debug: var=item
#with_items: "facter_blockdevices.split(',')"


- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: keypair_create

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var.yml
  roles:
    - role: token
    - role: lookup_name
    - role: eip_apply

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - tenant_var.yml
#  vars:
#    eip_id: "{{ eip_id }}"
  roles:
    - role: token
    - role: lookup_name
    - role: ecs_create
    - role: job
