- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/healthcheck"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/elb_healthcheck_create/templates/request.json.j2')|to_json }}" 
  register: elbhealthcheck
  when: listener_id is defined and listener_id|length != 0

- debug:
    msg: "{{ elbhealthcheck }}"

