- name: Lookup evs_id
  include: lookup.yml

- name: Send request to API (delete EVS)
  uri:
    url: "{{ AUTH_URL_EVS }}/cloudvolumes/{{ evs_id }}"
    method: DELETE
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    status_code: 200,201,202,203,204
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: evs

- debug:
    msg: "{{ evs }}"
