- name: Send request to API (list EVS)
  uri:
    url: "{{ AUTH_URL_EVS }}/cloudvolumes"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: volumeslist

- debug:
    msg: "{{ volumeslist.json }}"
