- name: Request rds list from API for mysql
  uri:
    url: "{{ AUTH_URL_RDS }}/{{ OS_USER_DOMAIN_ID }}/datastores/MySQL/versions"
    method: GET
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_Accept: "application/json"
    HEADER_X-Language: "en-us"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: rds_mysql_versions

- name: Request rds list from API for postgresql
  uri:
    url: "{{ AUTH_URL_RDS }}/{{ OS_USER_DOMAIN_ID }}/datastores/PostgreSQL/versions"
    method: GET
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_Accept: "application/json"
    HEADER_X-Language: "en-us"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: rds_postgresql_versions

- debug:
    msg: "{{ rds_mysql_versions.json }}"

- debug:
    msg: "{{ rds_postgresql_versions.json }}"
