# - include_vars: _ecs_secrets.yml

- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ECS_CLOUD }}/{{ PROJECT_ID }}/cloudservers"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/ecs_create/templates/request.json.j2')|to_json }}" 
  register: ecs

- set_fact:
    job_id: "{{ (ecs.content|from_json)|json_query('job_id') }}"
  when: ecs is defined

- debug:
    msg: "{{ job_id }}"

