- name: Get subnet_id
  include: lookup.yml
  when:
    - subnet_name is defined

- name: Send request to API (create subnet)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/subnets"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  when: 
    - subnet_name is defined
    - not subnet_id or subnet_id is undefined
  register: subnet

- debug:
    msg: "{{ subnet }}"
