- name: Request subnet list from API for ecs
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/subnets"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  when:
    - subnet_name is defined
  register: subnet_result

- name: Set fact for subnet_id if subnet_name is defined
  set_fact:
    subnet_id: "{{ (subnet_result.content|from_json)|json_query(\"subnets[?name=='\" + subnet_name + \"'].id|[0]\") }}"
  when:
    - subnet_name is defined and subnet_name|length != 0

