- name: Request endpoints list from AUTH API
  uri:
    url: "{{ IAM_AUTH_URL }}/endpoints"
    method: GET
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: endpointlist

- debug:
    msg: "{{ endpointlist.json }}"

