- include_vars: _secrets.yml

- name: Send request to API
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones/{{ zone_id }}/recordsets"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    status_code: 200,201,202,203
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/zonerecord_create/templates/request.json.j2')|to_json }}" 
  register: zonerecord
  when: zonerecord_type is defined

- debug:
    msg: "{{ zonerecord }}"

