- name: Send request to API
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/subnets"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/subnet_create/templates/request.json.j2')|to_json }}" 
  when: not subnet_id
  register: subnet

- debug:
    msg: "{{ subnet }}"

