- stat: path={{ keypair_file }}
  register: keypair_file_stat

- name: grab ssh pub key
  shell: awk '$1=$1' ORS='\\n' {{ keypair_file }}
  register: keypair_file_content
  when: keypair_file_stat.stat.exists

- name: Send request to API (create keypair)
  uri:
    url: "{{ AUTH_URL_ECS }}/os-keypairs"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  when:
    - keypair_file_stat.stat.exists
    - (not ecs_adminkey_name or ecs_adminkey_name is undefined)
  register: keypair

- debug:
    msg: "{{ keypair }}"
