- name: Send request to API (delete keypair)
  uri:
    url: "{{ AUTH_URL_ECS }}/os-keypairs/{{ ecs_adminkey }}"
    method: DELETE
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,204
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: keypair
  when: ecs_adminkey_name is defined and ecs_adminkey_name|length != 0
#  ignore_errors: true

- debug:
    msg: "{{ keypair }}"
