- name: Send request to API (keypair list)
  uri:
    url: "{{ AUTH_URL_ECS }}/os-keypairs"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: keypairlist
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: keypairlist.status == 200
  changed_when: false

- debug:
    msg: "{{ keypairlist.json }}"
