- name: Send request to API (keypair show)
  uri:
    url: "{{ AUTH_URL_ECS }}/os-keypairs/{{ ecs_adminkey }}"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: keypairdetail
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: keypairdetail.status == 200
  changed_when: false


- debug:
    msg: "{{ keypairdetail.json }}"
