- name: send ptrrecord request to API
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/reverse/floatingips/{{ PROJECT_NAME }}:{{ eip_id }}"
    method: PATCH
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,400
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/ptrrecord_create/templates/request.json.j2')|to_json }}"
  register: ptrrecord
  when: 
    - (ptr_name is defined and ptr_name | length != 0)
    - eip_id is defined

- debug:
    msg: "{{ ptrrecord }}"

