- name: Send request to API
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/vpcs"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  when:
    - not vpc_id or vpc_id is undefined
    - vpc_name is defined
  register: vpc

- debug:
    msg: "{{ vpc }}"
