- name: Lookup vpc_id
  include: lookup.yml

- name: Send request to API (delete VPC)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/vpcs/{{ vpc_id}}"
    method: DELETE
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,204
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: vpc
  when: vpc_id is defined and vpc_id|length != 0

- debug:
    msg: "{{ vpc }}"
  when: vpc_id is defined
