- name: Lookup vpc_id
  include: lookup.yml

- name: Send request to API (show VPC)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/vpcs/{{ vpc_id }}"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: vpcdetail
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: vpcdetail.status == 200
  changed_when: false
  when:
    - vpc_id is defined

- debug:
    msg: "{{ vpcdetail.json }}"
