- name: Lookup vpc_id
  include: lookup.yml

- name: Request router from API
  uri:
    url: "{{ AUTH_URL_VPC }}/v2.0/routers/{{ vpc_id }}"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  when:
    - vpc_id is defined
  register: routerlist

- set_fact:
    external_network_id: "{{ (routerlist.content|from_json)|json_query('router.external_gateway_info.network_id') }}"
  when: routerlist is defined

- name: Send request to API
  uri:
    url: "{{ AUTH_URL_VPC }}/v2.0/routers/{{ vpc_id }}"
    method: PUT
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'snat.json.j2')|to_json }}"
  when:
    - vpc_id is defined
    - enable_snat is defined
    - external_network_id|length != 0
  register: router

- debug:
    msg: "{{ router }}"
