- name: Lookup image_id
  include: lookup.yml

- name: Send request to API
  uri:
    url: "{{ AUTH_URL_IMS }}/v2/images/{{ image_id }}"
    method: DELETE
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: image_delete

- debug:
    msg: "{{ image_delete }}"
