- name: Request images list from  API
  uri:
    url: "{{ AUTH_URL_IMS }}/v2/cloudimages"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: imageslist

- debug:
    msg: "{{ imageslist.json }}"
