- name: Lookup image_id
  include: lookup.yml

- name: Request image detail from API
  uri:
    url: "{{ AUTH_URL_IMS }}/v2/images/{{ image_id }}"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: imagedetail
  when:
    - image_id is defined

- debug:
    msg: "{{ imagedetail.json }}"
