- name: Lookup zone_id
  include: lookup.yml

- name: Send request to API (delete zone)
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones/{{ zone_id }}"
    method: DELETE
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  when: zone_id is defined
  register: zone

- debug: var=zone.json
  when: zone is defined
