- name: Send request to API
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/publicips"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/eip_apply/templates/request.json.j2')|to_json }}" 
  register: eip

- set_fact: 
    public_ip_address: "{{ (eip.content|from_json)|json_query('publicip.public_ip_address') }}"

- debug:
    msg: "{{ public_ip_address }}"

