- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/listeners/{{ listener_id}}"
    method: DELETE
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,204
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elblistener

- debug:
    msg: "{{ elblistener }}"
