- name: Send request to API (delete ECS)
  uri:
    url: "{{ AUTH_URL_ECS_CLOUD }}/{{ PROJECT_ID }}/cloudservers/delete"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'delete.json.j2')|to_json }}"
  register: ecs
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: ecs.status == 200 
  changed_when: false
  when: ecs_id is defined and ecs_id|length != 0

- pause:
    minutes: 1

- debug:
    msg: "{{ ecs }}"
