- name: Send request to API (list ECS)
  uri:
    url: "{{ AUTH_URL_ECS }}/servers"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: ecslist
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: ecslist.status == 200 
  changed_when: false

- debug:
    msg: "{{ ecslist.json }}"
