- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ECS }}/servers/{{ ecs_id }}"
    method: PUT
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'ecsshow.json.j2')|to_json }}"
  register: ecs

- debug:
    msg: "{{ ecs }}"
