- name: Request single zone  from  API
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones/{{ zone_id }}"
    method: GET
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  when: zone_id is defined
  register: zone

- debug: var=zone.json
  when: zone is defined

- name: Request zone list from  API
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/zones"
    method: GET
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  when: zone_id is undefined
  register: zonelist

- debug: var=zonelist.json
  when: zonelist is defined
