---
- hosts: localhost
  gather_facts: no
  vars_files:
   - "vars/tenant.yml"
  vars:
      tenant_yml: "vars/tenant.yml"
#  roles:
#    - role: "../roles/otc_auth"
#    - role: "../roles/otc_ecs"
      localaction: "create"
      image_name: "{{ vms[ecs_name].image_name | default(default.image_name) }}"
      availability_zone: "{{ vms[ecs_name].availability_zone }} | default(default.availability_zone)"
      evs_availability_zone: "{{ vms[ecs_name].evs_availability_zone }} | default(default.evs_availability_zone)"
      vpc_name: "{{ vms[ecs_name].vpc_name }} | default(default.vpc_name)"
      vpc_net: "{{ vms[ecs_name].vpc_net }} | default(default.vpc_net)"
      subnet_name: "{{ vms[ecs_name].subnet_name }} | default(default.subnet_name)"
      subnet_net: "{{ vms[ecs_name].subnet_net }} | default(default.subnet_net)"
      subnet_gateway: "{{ vms[ecs_name].subnet_gateway }} | default(default.subnet_gateway)"
      subnet_dhcp_enable: "{{ vms[ecs_name].subnet_dhcp_enable }} | default(default.subnet_dhcp_enable)"
      subnet_primary_dns: "{{ vms[ecs_name].subnet_primary_dns }} | default(default.subnet_primary_dns)"
      subnet_secondary_dns: "{{ vms[ecs_name].subnet_secondary_dns }} | default(default.subnet_secondary_dns)"
      secgroup_name: "{{ vms[ecs_name].secgroup_name }} | default(default.secgroup_name)"
      secgroup_rule1: "{{ vms[ecs_name].secgroup_rule1 }} | default(default.secgroup_rule1)"
      ecs_volumetype: "{{ vms[ecs_name].ecs_volumetype }} | default(default.ecs_volumetype)"
      ecs_ram: "{{ vms[ecs_name].ecs_ram }} | default(default.ecs_ram)"
      ecs_vcpus: "{{ vms[ecs_name].ecs_vcpus }} | default(default.ecs_vcpus)"
      ecs_adminkey: "{{ vms[ecs_name].ecs_adminkey }} | default(default.ecs_adminkey)"
      keypair_file: "{{ vms[ecs_name].keypair_file }} | default(default.keypair_file)"

  tasks:
  - debug:
      msg: "{{ image_name }}"
