---
- hosts: localhost
  gather_facts: no
  vars:
    tenant_json: "vars/tenant.json"
    tenant_cf: "{{ lookup('file', tenant_json) | from_json }}"
    image_name: "{{ tenant_cf['vms'][ecs_name]['image_name'] | default(tenant_cf['default']['image_name']) }}"
    evs_availability_zone: "{{ tenant_cf['vms'][ecs_name]['evs_availability_zone'] | default(tenant_cf['default']['evs_availability_zone']) }}"
    vpc_name: "{{ tenant_cf['vms'][ecs_name]['vpc_name'] | default(tenant_cf['default']['vpc_name']) }}"
    vpc_net: "{{ tenant_cf['vms'][ecs_name]['vpc_net'] | default(tenant_cf['default']['vpc_net']) }}"
    subnet_name: "{{ tenant_cf['vms'][ecs_name]['subnet_name'] | default(tenant_cf['default']['subnet_name']) }}"
    subnet_net: "{{ tenant_cf['vms'][ecs_name]['subnet_net'] | default(tenant_cf['default']['subnet_net']) }}"
    subnet_gateway: "{{ tenant_cf['vms'][ecs_name]['subnet_gateway'] | default(tenant_cf['default']['subnet_gateway']) }}"
    subnet_dhcp_enable: "{{ tenant_cf['vms'][ecs_name]['subnet_dhcp_enable'] | default(tenant_cf['default']['subnet_dhcp_enable']) }}"
    subnet_primary_dns: "{{ tenant_cf['vms'][ecs_name]['subnet_primary_dns'] | default(tenant_cf['default']['subnet_primary_dns']) }}"
    subnet_secondary_dns: "{{ tenant_cf['vms'][ecs_name]['subnet_secondary_dns'] | default(tenant_cf['default']['subnet_secondary_dns']) }}"
    secgroups: "{{ tenant_cf['vms'][ecs_name]['secgroups'] | default(tenant_cf['default']['secgroups']) }}"
    secgrouprules: "{{ tenant_cf['securitygroups'][secgroup_name] }}"
    ecs_volumetype: "{{ tenant_cf['vms'][ecs_name]['ecs_volumetype'] | default(tenant_cf['default']['ecs_volumetype']) }}"
    ecs_ram: "{{ tenant_cf['vms'][ecs_name]['ecs_ram'] | default(tenant_cf['default']['ecs_ram']) }}"
    ecs_vcpus: "{{ tenant_cf['vms'][ecs_name]['ecs_vcpus'] | default(tenant_cf['default']['ecs_vcpus']) }}"
    ecs_adminkey: "{{ tenant_cf['vms'][ecs_name]['ecs_adminkey'] | default(tenant_cf['default']['ecs_adminkey']) }}"
    keypair_file: "{{ tenant_cf['vms'][ecs_name]['keypair_file'] | default(tenant_cf['default']['keypair_file']) }}"

  roles:
    - role: "../roles/otc_auth"
    - role: "../roles/otc_vpc"
    - role: "../roles/otc_secgroup"
      localaction: "delete"
    - role: "../roles/otc_secgroup"
      localaction: "create"

#  tasks:
#  - debug:
#      msg: "{{ secgroups }}"
