- name: Get elb_certificate_id
  include: certificatelookup.yml

- name: Send request to API (delete certificate)
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/certificate/{{ elb_certificate_id }}"
    method: DELETE
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,204
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elbcertifcate
  when: elb_certificate_id is defined and elb_certificate_id|length != 0

- debug:
    msg: "{{ elbcertifcate }}"
  when:
    - elbcertifcate is defined
    - elb_certificate_id is defined
