- name: Get elb_id
  include: lookup.yml
  when:
    - elb_name is defined

- name: Send request to API (create ELB)
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/loadbalancers"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  when:
    - listener_name is undefined
    - vpc_id is defined
    - elb_name is defined
    - not elb_id or elb_id is undefined
  register: elb

- debug:
    msg: "{{ elb }}"
