- name: Send request to API (Create ELB Healthcheck)
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/healthcheck"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'healthcheck_create.json.j2')|to_json }}"
  register: elbhealthcheck
  when: listener_id is defined and listener_id|length != 0

- debug:
    msg: "{{ elbhealthcheck }}"
