- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/healthcheck/{{ healthcheck_id }}"
    method: DELETE
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,204
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elbhealthcheck
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: elbhealthcheck.status == 200 or elbhealthcheck.status == 201 or elbhealthcheck.status == 203 or elbhealthcheck.status == 204
  changed_when: false

- debug:
    msg: "{{ elbhealthcheck }}"
