- name: Send request to API (create elb_listener)
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/listeners"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'listener_create.json.j2')|to_json }}"
  register: elblistner
  when:
    - elb_id is defined
    - listener_name is defined

# - pause:
#     minutes: 1

- debug:
    msg: "{{ elblistner }}"
