- name: Lookup elb_id
  include: lookup.yml

- name: Send request to API (show ELB)
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/loadbalancers/{{ elb_id }}"
    method: GET
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elb
  when: elb_id is defined

- debug:
    msg: "{{ elb }}"
