- name: Request rds flavors from API
  uri:
    url: "{{ AUTH_URL_RDS }}/{{ OS_USER_DOMAIN_ID }}/flavors?dbId={{ rds_version_id }}&region={{ PROJECT_NAME }}"
    method: GET
    return_content: yes
    validate_certs: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      X-Language: "en-us"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: rds_flavors

- debug:
    msg: "{{ rds_flavors.json }}"
