- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/certificate"
    method: GET
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elbcertificate

- set_fact:
    certificate_names: "{{ (elbcertificate.content|from_json)|json_query('certificates[].name') }}"

- debug:
#    msg: "{{ elbcertificate }}"
    msg: "{{ certificate_names }}"
  when: elbcertificate is defined
