- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB }}/{{ PROJECT_ID }}/elbaas/listeners"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/elb_listener_create/templates/request.json.j2')|to_json }}"
  register: elblistner
  when:
    - elb_id is defined
    - listener_name is defined

# - pause:
#     minutes: 1

- debug:
    msg: "{{ elblistner }}"
