- name: Send request to API
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/security-groups"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'request.json.j2')|to_json }}"
  when: (not secgroup_id and secgroup_name is defined)
  register: secgroup

- debug:
    msg: "{{ secgroup_id }}"
  when: secgroup_id is defined
