- name: send ptrrecord request to API
  uri:
    url: "{{ AUTH_URL_DNS }}/v2/reverse/floatingips"
    method: GET
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    status_code: 200,201,202,203,400
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: ptrrecord

- debug:
    msg: "{{ ptrrecord }}"
